<a href="https://colab.research.google.com/github/gautamprafful007/Deep-Learning-using-PyTorch/blob/main/00_pytorch_fundamentals_video.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
print(torch.__version__)

2.8.0+cu126


## Introduction to Tensors


Creating Tensors


Pytorch tensors are created using torch.Tensor() = https://docs.pytorch.org/docs/stable/tensors.html

In [ ]:
# scalar
scalar=torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
# Get tensor back as Python int
scalar.item()

7

In [ ]:
# Vector
vector=torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# MATRIX
matrix=torch.tensor([[7,8],
                     [10,9]])
matrix

tensor([[ 7,  8],
        [10,  9]])

In [ ]:
matrix.ndim

2

In [ ]:
matrix.shape

torch.Size([2, 2])

In [ ]:
matrix[1]

tensor([10,  9])

In [ ]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]],
                       [[2,4,3],
                       [4,3,7],
                       [9,0,4]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[2, 4, 3],
         [4, 3, 7],
         [9, 0, 4]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([2, 3, 3])

In [ ]:
TENSOR[1]

tensor([[2, 4, 3],
        [4, 3, 7],
        [9, 0, 4]])

### Random Tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

Start with random numbers --> look at data --> update random numbers --> look at data --> update random numbers

Torch random tensors :- https://docs.pytorch.org/docs/stable/generated/torch.rand.html

In [ ]:
# Create a random tensor of size (3,4)

random_tensor=torch.rand(3,4)
random_tensor

tensor([[0.8694, 0.5677, 0.7411, 0.4294],
        [0.8854, 0.5739, 0.2666, 0.6274],
        [0.2696, 0.4414, 0.2969, 0.8317]])

In [ ]:
random_tensor.ndim

2

In [ ]:
# Create a random tensor with similar shape to an image tensor

random_image_size_tensor=torch.rand(size=(3,224,224)) # color channel,height, width of an image
random_image_size_tensor.shape , random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

### Zeros and Ones

In [ ]:
# create a tensor of all zeros

zeros=torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
# create a tensor of all ones

ones=torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

###  Creating a range of Tensors and Tensors-like

In [ ]:
# Using torch.range() and get a depricated message,insteaduse torch.arange()

#one_to_ten=torch.arange(start=1,end=11,step=1)
one_to_ten=torch.arange(1,11,1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# Creating Tensors like
ten_zeroes=torch.zeros_like(one_to_ten)
ten_zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
ten_zeroes.shape

torch.Size([10])

### Tensor Data-Types

Note:Tensors datatypes has one of the three big errors you will run into with pytorch and deeplearning.


1.   Tensors not right data-type.
2.   Tensors not right shape.
3.   Tensors not on the right device.

Precision in Computing - https://en.wikipedia.org/wiki/Precision_(computer_science)


In [ ]:
# Float32 Tensor
float_32_tensor=torch.tensor([3.0,6.0,9.0],
                             dtype=None, # what data-type is a tensor e.g. float32,float16
                             device=None,# what device is your tensor on.
                             requires_grad=False) # whether or not to track gradients with this tensor operations.
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor=float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors


1.   Tensors not right datatypes - to get datatype from a tensor, can use tensor.dtype
2.   Tensors not right shape - to get shape from a tensor , can use tensor.shape
3.   Tensor not on the right device - to get device from a tensor , can use tensor.device



In [ ]:
# Create a tensor
#some_tensor=torch.rand(3,4,dtype=torch.int64)
some_tensor=torch.rand(3,4,dtype=torch.float16)
some_tensor

tensor([[0.4834, 0.5044, 0.0244, 0.8462],
        [0.5835, 0.5122, 0.5986, 0.6631],
        [0.8086, 0.7280, 0.4751, 0.3647]], dtype=torch.float16)

In [ ]:
print(some_tensor)
print(f'Datatype of some_tensor is {some_tensor.dtype}')
print(f'Shape of some_tensor is {some_tensor.shape}')
print(f'Device of some_tensor is {some_tensor.device}')

tensor([[0.4834, 0.5044, 0.0244, 0.8462],
        [0.5835, 0.5122, 0.5986, 0.6631],
        [0.8086, 0.7280, 0.4751, 0.3647]], dtype=torch.float16)
Datatype of some_tensor is torch.float16
Shape of some_tensor is torch.Size([3, 4])
Device of some_tensor is cpu


### Manipulating Tensors

Tensor Operation Includes


*   Addition
*   Subtraction
*   Multiplication (element-wise)
*   Division
*   Matrix Multiplication




In [ ]:
# Create a tensor and add 10 to it
tensor=torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
# Multiply a tensor by 10
tensor * 10

tensor([10, 20, 30])

In [ ]:
# Divide a tensor by 10
tensor / 10

tensor([0.1000, 0.2000, 0.3000])

In [ ]:
# Subtract a tensor by 10
tensor - 10

tensor([-9, -8, -7])

In [ ]:
# Try out pytorch in-built functions

torch.mul(tensor,11)

tensor([11, 22, 33])

In [ ]:
torch.add(tensor,7)

tensor([ 8,  9, 10])

### Matrix Multiplication

Two main ways of performing matrix multiplication in neural networks and deep learning are :


1.   Element wise Multiplication
2.   Matrix Multiplication (dot product)

The '@' symbol is another symbol that can be used to perform matrix multiplication

There are two main rules that performing matrix multiplication needs to satisfy:

1. The inner dimensions must match:


*   (3,2) @ (3,2) --> won't work
*   (3,2) @ (2,3) --> will work
*   (2,3) @ (3,2) --> will work

2.  The resulting matrix has the shape the outer dimensions

*   (2,3) @ (3,2) --> (2,2)
*   (3,2) @ (2,3) --> (3,3)

In [ ]:
torch.matmul(torch.rand(2,3),torch.rand(3,3))

tensor([[0.6382, 1.5370, 1.5237],
        [0.5702, 1.3574, 1.2901]])

In [ ]:
print(tensor, '*' ,tensor)
print(f'Equals : {tensor * tensor}')

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals : tensor([1, 4, 9])


In [ ]:
# Matrix Multiplication
torch.matmul(tensor,tensor)

tensor(14)

In [ ]:
tensor @ tensor

tensor(14)

In [ ]:
# Matrix Multiplication by hand

1*1 + 2*2 + 3*3

14

In [ ]:
%%time
value=0
for i in range(len(tensor)):
  value+= tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 966 µs, sys: 37 µs, total: 1 ms
Wall time: 1.48 ms


In [ ]:
%%time

torch.matmul(tensor,tensor)

CPU times: user 401 µs, sys: 0 ns, total: 401 µs
Wall time: 1.15 ms


tensor(14)

### One of the most common errors in Deep learning : shape errors

In [ ]:
tensor_A=torch.tensor([[1,2],
                       [3,4],
                       [5,6]])

tensor_B=torch.tensor([[7,10],
                       [8,11],
                       [9,12]])

torch.matmul(tensor_A,tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
tensor_A.shape,tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shape issues, we can manipulate the shape of one of our tensor using a **transpose**.

A Transpose switches the axis or dimensions of a tensor.

In [ ]:
tensor_B

tensor([[ 7, 10],
        [ 8, 11],
        [ 9, 12]])

In [ ]:
tensor_B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [ ]:
tensor_B.shape,tensor_B.T.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

In [ ]:
# Thematrix multiplication operation works when tensor_B is transposed.

print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape}(same as above), tensor_B.T = {tensor_B.T.shape}")

torch.matmul(tensor_A,tensor_B.T)

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2])(same as above), tensor_B.T = torch.Size([2, 3])


tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [ ]:
torch.matmul(tensor_A,tensor_B.T).shape

torch.Size([3, 3])

### Finding the min, max, mean, sum, etc(tensor aggregation)

In [ ]:
# Creating a tensor

x=torch.arange(0,100,10)
x , x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [ ]:
# Find the min
torch.min(x),x.min()

(tensor(0), tensor(0))

In [ ]:
# Find the max
torch.max(x),x.max()

(tensor(90), tensor(90))

In [ ]:
# Finding the mean

#torch.mean(x) mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

torch.mean(x,dtype=torch.float32) , x.mean(dtype=torch.float32)

(tensor(45.), tensor(45.))

In [ ]:
torch.sum(x),x.sum()

(tensor(450), tensor(450))

### Finding the Positional min and max

In [ ]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
x.argmin()

tensor(0)

In [ ]:
x.argmax()

tensor(9)

### Reshaping,Stacking,Squeezing and Unsqueezing Tensors
*  Reshaping - Reshapes an input tensor to a defined shape
*  View - Returns a view of an input tensor of certain shape but keeps the same memory as the original tensor
*  Stacking - Combine multiple tensors on top of each other (Vstack) or side by side of each other (Hstack)
*  Squeezing - Removes all `1` dimensions from a tensor
*  Unsqueezing - Add a `1` dimension to a tensor
*  Permute - Return a view of the input with dimensions permuted (swapped) in a certain way

In [ ]:
# Lets create a tensor
import torch
x=torch.arange(1.,10.)
x,x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
# Add an extra dimension
x_reshaped=x.reshape(1,9)
x_reshaped,x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# Change the view
z=x.view(1,9)
z,z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# Changing z changes x (because a view of a tensor shares the same memory as the original tensor)
z[:,0]=5.0
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
# Stack tensors on top of each other
x_stacked=torch.stack([x,x,x,x,x],dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
# torch.squeeze() - remove all single dimensions from the target tensor
print(f"Previous Tensor : {x_reshaped}")
print(f"Previous shape : {x_reshaped.shape}")

#Remove extra dimension from x_reshaped
x_squeezed=x_reshaped.squeeze()
print(f"\nNew Tensor : {x_squeezed}")
print(f"New Tensor shape : {x_squeezed.shape}")

Previous Tensor : tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape : torch.Size([1, 9])

New Tensor : tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New Tensor shape : torch.Size([9])


In [ ]:
# torch.unsqueeze() - adds a single dimension to a target tensorat a specific dimension
print(f"Previous Tensor : {x_squeezed}")
print(f"Previous shape : {x_squeezed.shape}")

# Add an extra dimension with unsqueeze()
x_unsqueezed=x_squeezed.unsqueeze(0)
print(f"\nNew Tensor : {x_unsqueezed}")
print(f"New shape : {x_unsqueezed.shape}")

Previous Tensor : tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape : torch.Size([9])

New Tensor : tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape : torch.Size([1, 9])


In [ ]:
# torch.permute() - rearranges the dimensions of a target tensor in a specified order
x_original=torch.rand(size=(224,224,3)) # (Height,width,color_channels)

# Permute the original tensor to rearrange the axis (or dim) order
x_permuted=x_original.permute(2,0,1) # shifts axis 0->1, 1->2, 2->0
print(f"Original shape : {x_original.shape}")
print(f"Permuted shape : {x_permuted.shape}") #[color_channels, height, width]

Original shape : torch.Size([224, 224, 3])
Permuted shape : torch.Size([3, 224, 224])


In [ ]:
# Change in x_original will also result in a change in x_permuted because they share the same memory .
# x_permute returns a `view` of the original tensor with its dimensions permuted.
x_original[0,0,0]=75348
x_original[0,0,0] , x_permuted[0,0,0]

(tensor(75348.), tensor(75348.))

### Indexing (Selecting data from tensors)
indexing with pytorch is similar to indexing with numpy

In [ ]:
# Create a tensor
import torch
x=torch.tensor([[[1,2,3],
                 [4,5,6],
                 [7,8,9]]])
x,x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
# Let's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
# Let's index on middle bracket (dim=1)
x[0][0]

tensor([1, 2, 3])

In [ ]:
# Let's index on the most inner bracket(Last dimension)
x[0][2][2]

tensor(9)

In [ ]:
# You can also use ':' to select "all" of the target dimension
x[:,0,2]

tensor([3])

In [ ]:
# Get all of 0th and 1st dimensions but only index 1 of 3rd dimension
x[:,:,1]

tensor([[2, 5, 8]])

In [ ]:
# Get all values of the 0 dimension but only the 1st index values of 1st and 2nd dimension
x[:,1,1]

tensor([5])

In [ ]:
# Get all the values of the 0 dimension but only the 1st index value of 1st and 2nd dimension
x[:,1,1]

tensor([5])

In [ ]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0,0,:]

tensor([1, 2, 3])

In [ ]:
# Index on x to return 9
x[0,2,2]

tensor(9)

In [ ]:
# Index on x to return [3,6,9]
x[:,:,2]

tensor([[3, 6, 9]])

### Pytorch tensors & Numpy
Numpy is a popular scientific python numerical computing library.
And because of this, Pytorch has functionality to interact with it.
* Data in Numpy, want in Pytorch tensor --> `torch.from_numpy(ndarray)`
* Pytorch tensor to Numpy --> `torch.tensor.numpy()`

In [ ]:
# Numpy array to tensor
import torch
import numpy as np
array=np.arange(1.0,11.0)
tensor=torch.from_numpy(array) #warning : when converting from numpy --> pytorch, pytorch reflects numpy's default dtype of float64 unless specified explicitily.
array,tensor

(array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]),
 tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=torch.float64))

In [ ]:
array.dtype

dtype('float64')

In [ ]:
tensor.dtype

torch.float64

In [ ]:
# Change the value of array. What will it do to a tensor ?
array = array + 1
array,tensor

(array([ 2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.]),
 tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=torch.float64))

In [ ]:
# tensor to numpy
tensor=torch.ones(7)
numpy_tensor=tensor.numpy()
tensor,numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
numpy_tensor.dtype

dtype('float32')

In [ ]:
# change the tensor . What happens to numpy_tensor?
tensor=tensor+1
numpy_tensor,tensor

(array([1., 1., 1., 1., 1., 1., 1.], dtype=float32),
 tensor([2., 2., 2., 2., 2., 2., 2.]))

## Reproducibility : Trying to take random out of random

In short how a neural networks learns:
`start with random numbers --> tensor operations --> update random numbers to try and make them better representations of data --> again --> again --> again ...`

To reduce the randomness in neural networks and PyTorch comes the concept of a **random seed**.

Essentially what the random seed does is "flavour" the randomness.

In [ ]:
torch.rand(3,3)

tensor([[0.0294, 0.5449, 0.0794],
        [0.2313, 0.2927, 0.3386],
        [0.3708, 0.0831, 0.0944]])

In [ ]:
import torch

# Create two random tensors
random_tensor_A=torch.rand(3,4)
random_tensor_B=torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)

print(random_tensor_A == random_tensor_B)

tensor([[0.6568, 0.7708, 0.1053, 0.1467],
        [0.1932, 0.9118, 0.1488, 0.0913],
        [0.4470, 0.2440, 0.5571, 0.1928]])
tensor([[6.0224e-02, 5.8370e-01, 8.6433e-04, 7.5808e-01],
        [5.8165e-01, 4.3382e-01, 3.3265e-02, 3.7463e-01],
        [7.1104e-01, 5.9461e-01, 9.4746e-01, 6.2281e-01]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
# Let's make some random but reproducable tensors
import torch

#Set the random seed
RANDOM_SEED=42
torch.manual_seed(RANDOM_SEED)
random_tensor_C=torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D=torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running Tensors and Pytorch objects on the GPUs(and making faster computations)
GPUs=faster computation on numbers, thanks to CUDA + NVDIA hardware + PyTorch working behind the scenes tomake exerything good.

In [ ]:
!nvidia-smi

Tue Sep  9 12:31:12 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   50C    P8             10W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

Check for GPU access with PyTorch

In [ ]:
# check for GPU access with pytorch
import torch
torch.cuda.is_available()

True

For PyTorch since its capable of running compute on the GPU or CPU, it's best practice to setup device agnostic code:
E.g.: Run on GPU if available , else default to GPU

In [ ]:
# Setup device agnostic code
device="cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
# Count the number of devices
torch.cuda.device_count()

1

## Putting Tensors and Models on the GPU
The reason we want our tensors/models on the GPU is because using a GPU results in faster Computations.

In [ ]:
# Create a tensor(default on the CPU)
tensor=torch.tensor([1,2,3])

#Tensor not on GPU
print(tensor,tensor.device)

tensor([1, 2, 3]) cpu


In [ ]:
# Move tensor to GPU(if available)
tensor_on_gpu=tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

## Moving Tensors Back To CPU


In [ ]:
# If tensor is on GPU, can't transform it to Numpy
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [ ]:
# To fix the GPU tensor with Numpy issues, we can first set it up to the CPU
tensor_back_on_cpu=tensor_on_gpu.cpu()
tensor_back_on_cpu , tensor_back_on_cpu.device

(tensor([1, 2, 3]), device(type='cpu'))

In [ ]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

## Exercises and Extra Curriculum
See Exercises and curriculum here:https://www.learnpytorch.io/00_pytorch_fundamentals/#exercises